document.addEventListener("touchstart",function(){},false);(function($){"use strict";var windw=$(window);var scrollup=$('.scrollup');windw.scroll(function(){if($(this).scrollTop()>100){scrollup.fadeIn();}else{scrollup.fadeOut();}});scrollup.on('click','',function(event){$("html, body").animate({scrollTop:0},600);return false;});})(jQuery);$(function(){$('.toggle-price-starter1-year').hide();$('.toggle-price-premium1-year').hide();$('.toggle-price-professional1-year').hide();$('.toggle-price-maximum1-year').hide();});function changePlanStarter1(plan){$('[class^="toggle-price-starter1"]').hide();$('.toggle-price-starter1-'+plan).show();}
function changePlanPremium1(plan){$('[class^="toggle-price-premium1"]').hide();$('.toggle-price-premium1-'+plan).show();}
function changePlanProfessional1(plan){$('[class^="toggle-price-professional1"]').hide();$('.toggle-price-professional1-'+plan).show();}
function changePlanMaximum1(plan){$('[class^="toggle-price-maximum1"]').hide();$('.toggle-price-maximum1-'+plan).show();}
$(function(){$('.toggle-price-starter2-year').hide();$('.toggle-price-standard2-year').hide();$('.toggle-price-premium2-year').hide();});function changePlanStarter2(plan){$('[class^="toggle-price-starter2"]').hide();$('.toggle-price-starter2-'+plan).show();}
function changePlanStandard2(plan){$('[class^="toggle-price-standard2"]').hide();$('.toggle-price-standard2-'+plan).show();}
function changePlanPremium2(plan){$('[class^="toggle-price-premium2"]').hide();$('.toggle-price-premium2-'+plan).show();}
$(function(){$('.toggle-price-starter3-year').hide();$('.toggle-price-standard3-year').hide();$('.toggle-price-premium3-year').hide();$('.switch-light.switch-light-1 input ~ a').css('right','50%');$('.switch-light.switch-light-2 input ~ a').css('right','50%');$('.switch-light.switch-light-3 input ~ a').css('right','50%');$('#planstarteryear').attr('checked',false);$('#planstandardyear').attr('checked',false);$('#planpremiumyear').attr('checked',false);});function changePlanStarter3(){if($('#planstarteryear').is(":checked")){$('.toggle-price-starter3-year').show();$('.toggle-price-starter3-month').hide();$('.switch-light.switch-light-1 input ~ a').css('right','0%');$('#planstarteryear').attr('checked',true);}
else{$('.toggle-price-starter3-month').show();$('.toggle-price-starter3-year').hide();$('.switch-light.switch-light-1 input ~ a').css('right','50%');$('#planstarteryear').attr('checked',false);}}
function changePlanStandard3(){if($('#planstandardyear').is(":checked")){$('.toggle-price-standard3-year').show();$('.toggle-price-standard3-month').hide();$('.switch-light.switch-light-2 input ~ a').css('right','0%');$('#planstandardyear').attr('checked',true);}
else{$('.toggle-price-standard3-month').show();$('.toggle-price-standard3-year').hide();$('.switch-light.switch-light-2 input ~ a').css('right','50%');$('#planstandardyear').attr('checked',false);}}
function changePlanPremium3(){if($('#planpremiumyear').is(":checked")){$('.toggle-price-premium3-year').show();$('.toggle-price-premium3-month').hide();$('.switch-light.switch-light-3 input ~ a').css('right','0%');$('#planpremiumyear').attr('checked',true);}
else{$('.toggle-price-premium3-month').show();$('.toggle-price-premium3-year').hide();$('.switch-light.switch-light-3 input ~ a').css('right','50%');$('#planpremiumyear').attr('checked',false);}}
$(function(){$('.toggle-price-starter4-year').hide();$('.toggle-price-standard4-year').hide();$('.toggle-price-premium4-year').hide();$('.switch-light.switch-light-11 input ~ a').css('right','50%');$('.switch-light.switch-light-22 input ~ a').css('right','50%');$('.switch-light.switch-light-33 input ~ a').css('right','50%');$('#planstarteryear4').attr('checked',false);$('#planstandardyear4').attr('checked',false);$('#planpremiumyear4').attr('checked',false);});function changePlanStarter4(){if($('#planstarteryear4').is(":checked")){$('.toggle-price-starter4-year').show();$('.toggle-price-starter4-month').hide();$('.switch-light.switch-light-11 input ~ a').css('right','0%');$('#planstarteryear4').attr('checked',true);}
else{$('.toggle-price-starter4-month').show();$('.toggle-price-starter4-year').hide();$('.switch-light.switch-light-11 input ~ a').css('right','50%');$('#planstarteryear4').attr('checked',false);}}
function changePlanStandard4(){if($('#planstandardyear4').is(":checked")){$('.toggle-price-standard4-year').show();$('.toggle-price-standard4-month').hide();$('.switch-light.switch-light-22 input ~ a').css('right','0%');$('#planstandardyear4').attr('checked',true);}
else{$('.toggle-price-standard4-month').show();$('.toggle-price-standard4-year').hide();$('.switch-light.switch-light-22 input ~ a').css('right','50%');$('#planstandardyear4').attr('checked',false);}}
function changePlanPremium4(){if($('#planpremiumyear4').is(":checked")){$('.toggle-price-premium4-year').show();$('.toggle-price-premium4-month').hide();$('.switch-light.switch-light-33 input ~ a').css('right','0%');$('#planpremiumyear4').attr('checked',true);}
else{$('.toggle-price-premium4-month').show();$('.toggle-price-premium4-year').hide();$('.switch-light.switch-light-33 input ~ a').css('right','50%');$('#planpremiumyear4').attr('checked',false);}}
$(function(){$('.toggle-price-starter5-year').hide();$('.toggle-price-premium5-year').hide();$('.toggle-price-professional5-year').hide();$('.toggle-price-maximum5-year').hide();});function changePlanStarter5(plan){$('[class^="toggle-price-starter5"]').hide();$('.toggle-price-starter5-'+plan).show();}
function changePlanPremium5(plan){$('[class^="toggle-price-premium5"]').hide();$('.toggle-price-premium5-'+plan).show();}
function changePlanProfessional5(plan){$('[class^="toggle-price-professional5"]').hide();$('.toggle-price-professional5-'+plan).show();}
function changePlanMaximum5(plan){$('[class^="toggle-price-maximum5"]').hide();$('.toggle-price-maximum5-'+plan).show();}
$(function(){$('.toggle-price-starter6-year').hide();$('.toggle-price-standard6-year').hide();$('.toggle-price-premium6-year').hide();});function changePlanStarter6(plan){$('[class^="toggle-price-starter6"]').hide();$('.toggle-price-starter6-'+plan).show();}
function changePlanStandard6(plan){$('[class^="toggle-price-standard6"]').hide();$('.toggle-price-standard6-'+plan).show();}
function changePlanPremium6(plan){$('[class^="toggle-price-premium6"]').hide();$('.toggle-price-premium6-'+plan).show();}
$(function(){$('.toggle-price-starter7-year').hide();$('.toggle-price-standard7-year').hide();$('.toggle-price-premium7-year').hide();$('.switch-light.switch-light7-1 input ~ a').css('right','50%');$('.switch-light.switch-light7-2 input ~ a').css('right','50%');$('.switch-light.switch-light7-3 input ~ a').css('right','50%');$('#planstarteryear7').attr('checked',false);$('#planstandardyear7').attr('checked',false);$('#planpremiumyear7').attr('checked',false);});function changePlanStarter7(){if($('#planstarteryear7').is(":checked")){$('.toggle-price-starter7-year').show();$('.toggle-price-starter7-month').hide();$('.switch-light.switch-light7-1 input ~ a').css('right','0%');$('#planstarteryear7').attr('checked',true);}
else{$('.toggle-price-starter7-month').show();$('.toggle-price-starter7-year').hide();$('.switch-light.switch-light7-1 input ~ a').css('right','50%');$('#planstarteryear7').attr('checked',false);}}
function changePlanStandard7(){if($('#planstandardyear7').is(":checked")){$('.toggle-price-standard7-year').show();$('.toggle-price-standard7-month').hide();$('.switch-light.switch-light7-2 input ~ a').css('right','0%');$('#planstandardyear7').attr('checked',true);}
else{$('.toggle-price-standard7-month').show();$('.toggle-price-standard7-year').hide();$('.switch-light.switch-light7-2 input ~ a').css('right','50%');$('#planstandardyear7').attr('checked',false);}}
function changePlanPremium7(){if($('#planpremiumyear7').is(":checked")){$('.toggle-price-premium7-year').show();$('.toggle-price-premium7-month').hide();$('.switch-light.switch-light7-3 input ~ a').css('right','0%');$('#planpremiumyear7').attr('checked',true);}
else{$('.toggle-price-premium7-month').show();$('.toggle-price-premium7-year').hide();$('.switch-light.switch-light7-3 input ~ a').css('right','50%');$('#planpremiumyear7').attr('checked',false);}}
$(function(){$('.toggle-price-starter8-year').hide();$('.toggle-price-standard8-year').hide();$('.toggle-price-premium8-year').hide();$('.switch-light.switch-light8-1 input ~ a').css('right','50%');$('.switch-light.switch-light8-2 input ~ a').css('right','50%');$('.switch-light.switch-light8-3 input ~ a').css('right','50%');$('#planstarteryear8').attr('checked',false);$('#planstandardyear8').attr('checked',false);$('#planpremiumyear8').attr('checked',false);});function changePlanStarter8(){if($('#planstarteryear8').is(":checked")){$('.toggle-price-starter8-year').show();$('.toggle-price-starter8-month').hide();$('.switch-light.switch-light8-1 input ~ a').css('right','0%');$('#planstarteryear8').attr('checked',true);}
else{$('.toggle-price-starter8-month').show();$('.toggle-price-starter8-year').hide();$('.switch-light.switch-light8-1 input ~ a').css('right','50%');$('#planstarteryear8').attr('checked',false);}}
function changePlanStandard8(){if($('#planstandardyear8').is(":checked")){$('.toggle-price-standard8-year').show();$('.toggle-price-standard8-month').hide();$('.switch-light.switch-light8-2 input ~ a').css('right','0%');$('#planstandardyear8').attr('checked',true);}
else{$('.toggle-price-standard8-month').show();$('.toggle-price-standard8-year').hide();$('.switch-light.switch-light8-2 input ~ a').css('right','50%');$('#planstandardyear8').attr('checked',false);}}
function changePlanPremium8(){if($('#planpremiumyear8').is(":checked")){$('.toggle-price-premium8-year').show();$('.toggle-price-premium8-month').hide();$('.switch-light.switch-light8-3 input ~ a').css('right','0%');$('#planpremiumyear8').attr('checked',true);}
else{$('.toggle-price-premium8-month').show();$('.toggle-price-premium8-year').hide();$('.switch-light.switch-light8-3 input ~ a').css('right','50%');$('#planpremiumyear8').attr('checked',false);}}
$(function(){$('.toggle-price-starter9-year').hide();$('.toggle-price-premium9-year').hide();$('.toggle-price-professional9-year').hide();$('.toggle-price-maximum9-year').hide();});function changePlanStarter9(plan){$('[class^="toggle-price-starter9"]').hide();$('.toggle-price-starter9-'+plan).show();}
function changePlanPremium9(plan){$('[class^="toggle-price-premium9"]').hide();$('.toggle-price-premium9-'+plan).show();}
function changePlanProfessional9(plan){$('[class^="toggle-price-professional9"]').hide();$('.toggle-price-professional9-'+plan).show();}
function changePlanMaximum9(plan){$('[class^="toggle-price-maximum9"]').hide();$('.toggle-price-maximum9-'+plan).show();}
$(function(){$('.toggle-price-starterTen-year').hide();$('.toggle-price-standardTen-year').hide();$('.toggle-price-premiumTen-year').hide();});function changePlanStarterTen(plan){$('[class^="toggle-price-starterTen"]').hide();$('.toggle-price-starterTen-'+plan).show();}
function changePlanStandardTen(plan){$('[class^="toggle-price-standardTen"]').hide();$('.toggle-price-standardTen-'+plan).show();}
function changePlanPremiumTen(plan){$('[class^="toggle-price-premiumTen"]').hide();$('.toggle-price-premiumTen-'+plan).show();}
$(function(){$('.toggle-price-starterEleven-year').hide();$('.toggle-price-standardEleven-year').hide();$('.toggle-price-premiumEleven-year').hide();$('.switch-light.switch-light11-1 input ~ a').css('right','50%');$('.switch-light.switch-light11-2 input ~ a').css('right','50%');$('.switch-light.switch-light11-3 input ~ a').css('right','50%');$('#planstarteryearEleven').attr('checked',false);$('#planstandardyearEleven').attr('checked',false);$('#planpremiumyearEleven').attr('checked',false);});function changePlanStarterEleven(){if($('#planstarteryearEleven').is(":checked")){$('.toggle-price-starterEleven-year').show();$('.toggle-price-starterEleven-month').hide();$('.switch-light.switch-light11-1 input ~ a').css('right','0%');$('#planstarteryearEleven').attr('checked',true);}
else{$('.toggle-price-starterEleven-month').show();$('.toggle-price-starterEleven-year').hide();$('.switch-light.switch-light11-1 input ~ a').css('right','50%');$('#planstarteryearEleven').attr('checked',false);}}
function changePlanStandardEleven(){if($('#planstandardyearEleven').is(":checked")){$('.toggle-price-standardEleven-year').show();$('.toggle-price-standardEleven-month').hide();$('.switch-light.switch-light11-2 input ~ a').css('right','0%');$('#planstandardyearEleven').attr('checked',true);}
else{$('.toggle-price-standardEleven-month').show();$('.toggle-price-standardEleven-year').hide();$('.switch-light.switch-light11-2 input ~ a').css('right','50%');$('#planstandardyearEleven').attr('checked',false);}}
function changePlanPremiumEleven(){if($('#planpremiumyearEleven').is(":checked")){$('.toggle-price-premiumEleven-year').show();$('.toggle-price-premiumEleven-month').hide();$('.switch-light.switch-light11-3 input ~ a').css('right','0%');$('#planpremiumyearEleven').attr('checked',true);}
else{$('.toggle-price-premiumEleven-month').show();$('.toggle-price-premiumEleven-year').hide();$('.switch-light.switch-light11-3 input ~ a').css('right','50%');$('#planpremiumyearEleven').attr('checked',false);}}
$(function(){$('.toggle-price-starterTwelve-year').hide();$('.toggle-price-standardTwelve-year').hide();$('.toggle-price-premiumTwelve-year').hide();$('.switch-light.switch-light12-1 input ~ a').css('right','50%');$('.switch-light.switch-light12-2 input ~ a').css('right','50%');$('.switch-light.switch-light12-3 input ~ a').css('right','50%');$('#planstarteryearTwelve').attr('checked',false);$('#planstandardyearTwelve').attr('checked',false);$('#planpremiumyearTwelve').attr('checked',false);});function changePlanStarterTwelve(){if($('#planstarteryearTwelve').is(":checked")){$('.toggle-price-starterTwelve-year').show();$('.toggle-price-starterTwelve-month').hide();$('.switch-light.switch-light12-1 input ~ a').css('right','0%');$('#planstarteryearTwelve').attr('checked',true);}
else{$('.toggle-price-starterTwelve-month').show();$('.toggle-price-starterTwelve-year').hide();$('.switch-light.switch-light12-1 input ~ a').css('right','50%');$('#planstarteryearTwelve').attr('checked',false);}}
function changePlanStandardTwelve(){if($('#planstandardyearTwelve').is(":checked")){$('.toggle-price-standardTwelve-year').show();$('.toggle-price-standardTwelve-month').hide();$('.switch-light.switch-light12-2 input ~ a').css('right','0%');$('#planstandardyearTwelve').attr('checked',true);}
else{$('.toggle-price-standardTwelve-month').show();$('.toggle-price-standardTwelve-year').hide();$('.switch-light.switch-light12-2 input ~ a').css('right','50%');$('#planstandardyearTwelve').attr('checked',false);}}
function changePlanPremiumTwelve(){if($('#planpremiumyearTwelve').is(":checked")){$('.toggle-price-premiumTwelve-year').show();$('.toggle-price-premiumTwelve-month').hide();$('.switch-light.switch-light12-3 input ~ a').css('right','0%');$('#planpremiumyearTwelve').attr('checked',true);}
else{$('.toggle-price-premiumTwelve-month').show();$('.toggle-price-premiumTwelve-year').hide();$('.switch-light.switch-light12-3 input ~ a').css('right','50%');$('#planpremiumyearTwelve').attr('checked',false);}}